name: Manhunt
version: 1.0
main: com.laudynetwork.manhunt.Manhunt
api-version: '1.20'

dependencies:
  - name: NetworkUtils
    required: true
  - name: GameEngine
    required: true

load-after:
  - name: NetworkUtils
  - name: GameEngine